name: Build and Push Docker image

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
      push:
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    strategy:
      fail-fast: false
      matrix:
        platform_tag: ["manylinux_2_38", "musllinux_1_2"]
        python:
          - { version: "3.9", abi: "cp39" }
          - { version: "3.10", abi: "cp310" }
          - { version: "3.11", abi: "cp311" }
          - { version: "3.12", abi: "cp312" }
          - { version: "3.13", abi: "cp313" }
          - { version: "3.13", abi: "cp313t" }

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag
        run: |
          branch=${{ github.event.inputs.branch }}
          tag=${branch#arrow_}

          manylinux=${{ matrix.platform_tag }}
          platform=$(echo $manylinux | cut -d '_' -f1)
          manylinux=${manylinux#*_}

          vcpkg=$(grep '^VCPKG=' .env | sed -E 's/^VCPKG="([^"]+)".*/\1/')

          echo "tag=${tag}" >> $GITHUB_ENV
          echo "manylinux=${manylinux}" >> $GITHUB_ENV
          echo "platform=${platform}" >> $GITHUB_ENV
          echo "vcpkg=${vcpkg}" >> $GITHUB_ENV


      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci/docker/python-wheel-${{ env.platform }}-full.dockerfile
          platforms: linux/loong64
          push: ${{ github.event.inputs.push }}
          build-args: |
            arch=loongarch64
            arch_short=loong64
            base=ghcr.io/loongson-cloud-community/arrow-wheel-${{ env.platform }}-vcpkg-flight-dev
            manylinux=${{ env.manylinux }}
            python=${{ matrix.python.version }}
            python_abi_tag=${{ matrix.python.abi }}
            vcpkg=${{ env.vcpkg }}
            loongarch_pip_url=https://lpypi.loongnix.cn/loongson/pypi/+simple
          tags: |
            ghcr.io/loongson-cloud-community/loong64-python-${{ matrix.python.version }}-wheel-${{ matrix.platform_tag }}-vcpkg-${{ env.vcpkg }}:latest
            ghcr.io/loongson-cloud-community/loong64-python-${{ matrix.python.version }}-wheel-${{ matrix.platform_tag }}-vcpkg-${{ env.vcpkg }}:${{ env.tag }}
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
